dist: trusty
sudo: required
language: ruby
rvm:
  - 2.5.1
cache: bundler
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo ./ubuntu.sh
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
script:
  - plantuml -testdot
